### ISSUE TITLE
Parenthesis in a search phrase will throw an error

### ISSUE THREAD

**Issue by M3nt3** [neo4j-apps/neo4j-bloom#22] opened 2020-12-11 09:14 UTC
apparently adding parenthesis to a serach frase will make the query fail.
The only difference between the snapshots is that I removed the parenthesis and added a coma in the "Search Phrase" field.

![image](https://user-images.githubusercontent.com/30655577/101884767-185d5a80-3b91-11eb-83ed-a3f321f209f5.png)
![image](https://user-images.githubusercontent.com/30655577/101884777-1dbaa500-3b91-11eb-92f5-83b4f5d9b5db.png)
![image](https://user-images.githubusercontent.com/30655577/101884856-36c35600-3b91-11eb-8976-ae119427b4b7.png)

**Comment by jharris4** [comment] 2020-12-14 14:53
@M3nt3 thanks for reporting the issue! We're not seeing this issue against newer versions of Neo4j. Would you mind sharing with us the version of the database you were running Bloom against when you encountered this issue?

**Comment by M3nt3** [comment] 2020-12-15 09:17
Hello and thanks for answering.
We are running Bloom Server (Neo4j Bloom version: 1.3.1) and I am connected through Chrome.

On top of the above, I noticed a related but different behaviour, that cause a worse crash.
I created a new Search with parenthesis, but this time I put the parameter within parenthesis:

![image](https://user-images.githubusercontent.com/30655577/102194372-2541bd00-3eb5-11eb-8fa9-95f45c9e658c.png)

Now I cannot run any search at all, as the search bar times out without matching any search phrase. This as soon as I start typing anything at all, even a normal query and not a search phrase. Bloom remains freezed until I actually modify that search phrase and remove the parenthesis.

![image](https://user-images.githubusercontent.com/30655577/102193768-67b6ca00-3eb4-11eb-8ccf-f4c75f51ab4c.png)

If I move the parameter outside those parentheses, I reproduce the same as above and only this query fails, with no timeout:
![image](https://user-images.githubusercontent.com/30655577/102195683-d137d800-3eb6-11eb-8f31-3a1376c87b58.png)

Thanks for checking this out.

**Comment by jharris4** [comment] 2020-12-15 13:23
Hi, thanks for the clear instructions! We can reproduce the new error you mentioned and we will investigate further.

As for the original issue, sorry I should have been more clear! Can you please report the version of the database (and not Bloom version) when you see the original error?

You can find the Neo4j database version from the Perspective Gallery like in the screenshot below:

<img width="841" alt="Screen Shot 2020-12-15 at 1 20 21 PM" src="https://user-images.githubusercontent.com/7042043/102220197-64353a00-3ed8-11eb-888e-b3657d675fbb.png">

This can be opened by clicking the top button in the menu bar on the left, and then clicking the title/name of your current perspective at the top of the panel that is open...

**Comment by M3nt3** [comment] 2020-12-15 14:27
Hi!
Apologise, did not think about specifying the Neo4j version.
We are running **4.0.4**

Thanks for looking into it.
It is not a huge problem avoiding parenthesis to be on the safe side, but I can see this being a nasty bug to find out as it is strange to think it comes from spelling (probably related to the parenthesis notation of nodes in cypher?).

**Comment by jharris4** [comment] 2020-12-15 14:58
Yeah, parenthesis notation can be tricky both because of its use in cypher, and because it is used for grouping in regular expressions.

Thanks for providing your Neo4j version, it'll help us narrow down the reproduction for the original/first issue you reported.

**Comment by jharris4** [comment] 2021-01-07 09:55
@M3nt3 We have just released Bloom version `1.5.0` which includes some fixes for special characters in search phrase text. If you have a moment to try it out it would be great if you could let us know if you can still reproduce the issue. Thanks!

**Comment by joknelid** [comment] 2021-04-29 12:16
Tested with `1.6.1` and works fine, going to close this issue

**Closed as completed by joknelid** 2021-04-29 12:16 UTC
