### ISSUE TITLE
Deeplinks fail to work

### ISSUE THREAD

**Issue by wolfgang-ldc** [neo4j-apps/neo4j-bloom#19] opened 2020-10-01 01:13 UTC
Hi,

ever since an upgrade to Neo4j Desktop 1.3.8 I cannot get deep links into Bloom to work. The database version is 4.1.1. Here are some of the deep link examples I have been using:
neo4j://graphapps/neo4j-bloom/%5b?search=MRG002&perspective=NewFoundation%5d
neo4j://graphapps/neo4j-bloom/%5b?search=Event%20by%2024734&perspective=NewFoundation%5d
neo4j://graphapps/neo4j-bloom/%5b?search=SourceReference%20by%2024726&perspective=NewFoundation%5d

Pre-defined searches in Bloom work fine, but just cannot get them to initiate via a hyperlink.

Any idea what might wrong here? Am I doing something wrong? Was hoping the latest upgrade would solve the issues, but it didn't. Any help is appreciated.

Wolfgang - Live Data Concepts

**Comment by joknelid** [comment] 2020-10-07 15:55
Hi!

Try removing the `[` and `]` from the URL:s, so first one for example would be `neo4j://graphapps/neo4j-bloom/?search=MRG002&perspective=NewFoundation`

**Comment by wolfgang-ldc** [comment] 2020-10-07 16:17
Hi Jens,

it seems that this particular example works as long as Bloom isn’t already running. If I try to use this example with a different name while Bloom is already open, nothing happens. If I close Bloom, then execute the link it opens fine again and finds the item.
Unfortunately Bloom will usually already be open most of the time and one just wants to add to an already existing visualization.

I tried this also with a predefined search which exists in this perspective, in that case if Bloom is not yet running Bloom opens but ends up displaying a blank screen. Here is the link I had used:
neo4j://graphapps/neo4j-bloom/?search=Event%20by%2024708&perspective=NewFoundation <neo4j://graphapps/neo4j-bloom/?search=Event%20by%2024708&perspective=NewFoundation>
If Bloom was already running nothing seems to happen.

Thanks for looking into this :-) It is a really important use case.

Wolfgang

**Comment by joknelid** [comment] 2020-10-19 14:42
Hi again!

I was able to reproduce this and will open a ticket in our internal tracking. Basically our code doesn't handle deep links after Bloom has been finished connecting. Sorry I didn't see this sooner, missed it since it's not reported as a new issue

**Comment by wolfgang-ldc** [comment] 2020-10-20 22:40
Hi Jens,

thanks for getting back to me, wasn’t sure whether my reply to your initial message was seen. Glad that it is now noted as a new issue, especially since Anurag mentioned deep links today as a feature in his talk at NODES 2020. Looking forward to a fix in a future release.

Best,

Wolfgang

**Comment by bitbuck3t** [comment] 2021-04-15 21:38
Hi Jens,

I just came across this issue and wanted to see if there were any updates or a timeline on when this might be fixed? Is there a feature bounty program that could help prioritize this issue?

Cheers!

**Comment by joknelid** [comment] 2021-04-22 13:00
Hi,

This issue has been fixed and will be released in Bloom 1.6.0, which will be out sometime in the next few weeks. Hope that helps :)

**Comment by bitbuck3t** [comment] 2021-04-22 14:33
Thanks so much for the update!

**Comment by wolfgang-ldc** [comment] 2021-04-28 02:02
yeah, thank you for getting it fixed, looking forward to it 👏🏻

**Comment by joknelid** [comment] 2021-04-29 12:10
Closing since this is fixed in 1.6.0 which was released yesterday

**Closed as completed by joknelid** 2021-04-29 12:10 UTC
